# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDB4-9mWXfDSUltgIhmYLDcp5RV0epp_
"""
import joblib
import numpy as np
import cv2
import gradio as gr

# Load model
model = joblib.load("model.joblib")

# Class labels
unique_labels = [
    'Bacterial_dermatosis', 'Fungal_infections', 'Healthy',
    'Hypersensitivity_allergic_dermatosis', 'cataract', 'cherry_eye',
    'conjunctivitis', 'glaucoma', 'iris_atrophy'
]

def predict(image):
    image = np.array(image)
    image = cv2.resize(image, (128, 128))
    image = image / 255.0
    image = np.expand_dims(image, axis=0)

    pred = model.predict(image)
    predicted_class = np.argmax(pred)
    predicted_label = unique_labels[predicted_class]

    return predicted_label

# Gradio interface (Gradio 4.x+ syntax)
interface = gr.Interface(
    fn=predict,
    inputs=gr.Image(label="Take a photo or upload an image"),
    outputs="text",
    title="Dog Disease Classifier",
    description="Use your phone's camera or upload an image of a dog's skin or eye condition to get a disease prediction."
)

interface.launch()

